version: "2"

services:
  web:
    container_name: web
    image: php:apache-pdo
    build: .
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html/
    
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./src:/var/www
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-tier
    ports:
      - 33060:3306

networks:
  app-tier:
    driver: bridge
